name: env_ReadCurrent
channels:
  - pytorch
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pytorch=1.12.1
  - torchvision=0.13
  - torchaudio=0.12
  - cudatoolkit=11.6
  - minimap2=2.17
  - samtools=1.16
  - snakemake=7.32
  - ont-fast5-api=4.1.1
  - scikit-learn=1.2
  - matplotlib
  - tqdm
